export const V2_TRANSPARENT_ALPHA_INDEX_NPC_CHARACTER = 100;
export const V2_TRANSPARENT_ALPHA_INDEX_PRIMARY_BEAM = 150;
export const V2_TRANSPARENT_ALPHA_INDEX_SPATIAL = 200;
export const V2_TRANSPARENT_ALPHA_INDEX_PLAYER_CHARACTER = 300;
