export const V2_TRANSPARENT_ALPHA_INDEX_NPC_CHARACTER = 100;
export const V2_TRANSPARENT_ALPHA_INDEX_BEAM_COLOR = 150;
export const V2_TRANSPARENT_ALPHA_INDEX_BEAM_DEPTH = 160;
export const V2_TRANSPARENT_ALPHA_INDEX_SPATIAL = 200;
export const V2_TRANSPARENT_ALPHA_INDEX_PLAYER_CHARACTER = 300;
